spring.application.name=Ecommerce
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=fender07ABCD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
security.jwt.secret-key=ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGYxZQ==
security.jwt.expiration-time=86400000